language: node_js
node_js:
  - '0.12'
sudo: false
addons:
  sauce_connect: true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower
  - bower install
script: gulp ci
